// Code generated by go-swagger; DO NOT EDIT.

package triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/projectodd/kwsk/models"
)

// DeleteTriggerHandlerFunc turns a function with the right signature into a delete trigger handler
type DeleteTriggerHandlerFunc func(DeleteTriggerParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteTriggerHandlerFunc) Handle(params DeleteTriggerParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteTriggerHandler interface for that can handle valid delete trigger params
type DeleteTriggerHandler interface {
	Handle(DeleteTriggerParams, *models.Principal) middleware.Responder
}

// NewDeleteTrigger creates a new http.Handler for the delete trigger operation
func NewDeleteTrigger(ctx *middleware.Context, handler DeleteTriggerHandler) *DeleteTrigger {
	return &DeleteTrigger{Context: ctx, Handler: handler}
}

/*DeleteTrigger swagger:route DELETE /namespaces/{namespace}/triggers/{triggerName} Triggers deleteTrigger

Delete a trigger

Delete a trigger

*/
type DeleteTrigger struct {
	Context *middleware.Context
	Handler DeleteTriggerHandler
}

func (o *DeleteTrigger) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteTriggerParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
