// Code generated by go-swagger; DO NOT EDIT.

package triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/projectodd/kwsk/models"
)

// GetTriggerByNameOKCode is the HTTP code returned for type GetTriggerByNameOK
const GetTriggerByNameOKCode int = 200

/*GetTriggerByNameOK Returned trigger

swagger:response getTriggerByNameOK
*/
type GetTriggerByNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Trigger `json:"body,omitempty"`
}

// NewGetTriggerByNameOK creates GetTriggerByNameOK with default headers values
func NewGetTriggerByNameOK() *GetTriggerByNameOK {

	return &GetTriggerByNameOK{}
}

// WithPayload adds the payload to the get trigger by name o k response
func (o *GetTriggerByNameOK) WithPayload(payload *models.Trigger) *GetTriggerByNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get trigger by name o k response
func (o *GetTriggerByNameOK) SetPayload(payload *models.Trigger) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTriggerByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTriggerByNameUnauthorizedCode is the HTTP code returned for type GetTriggerByNameUnauthorized
const GetTriggerByNameUnauthorizedCode int = 401

/*GetTriggerByNameUnauthorized Unauthorized request

swagger:response getTriggerByNameUnauthorized
*/
type GetTriggerByNameUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetTriggerByNameUnauthorized creates GetTriggerByNameUnauthorized with default headers values
func NewGetTriggerByNameUnauthorized() *GetTriggerByNameUnauthorized {

	return &GetTriggerByNameUnauthorized{}
}

// WithPayload adds the payload to the get trigger by name unauthorized response
func (o *GetTriggerByNameUnauthorized) WithPayload(payload *models.ErrorMessage) *GetTriggerByNameUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get trigger by name unauthorized response
func (o *GetTriggerByNameUnauthorized) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTriggerByNameUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTriggerByNameNotFoundCode is the HTTP code returned for type GetTriggerByNameNotFound
const GetTriggerByNameNotFoundCode int = 404

/*GetTriggerByNameNotFound Item not found

swagger:response getTriggerByNameNotFound
*/
type GetTriggerByNameNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetTriggerByNameNotFound creates GetTriggerByNameNotFound with default headers values
func NewGetTriggerByNameNotFound() *GetTriggerByNameNotFound {

	return &GetTriggerByNameNotFound{}
}

// WithPayload adds the payload to the get trigger by name not found response
func (o *GetTriggerByNameNotFound) WithPayload(payload *models.ErrorMessage) *GetTriggerByNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get trigger by name not found response
func (o *GetTriggerByNameNotFound) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTriggerByNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTriggerByNameInternalServerErrorCode is the HTTP code returned for type GetTriggerByNameInternalServerError
const GetTriggerByNameInternalServerErrorCode int = 500

/*GetTriggerByNameInternalServerError Server error

swagger:response getTriggerByNameInternalServerError
*/
type GetTriggerByNameInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetTriggerByNameInternalServerError creates GetTriggerByNameInternalServerError with default headers values
func NewGetTriggerByNameInternalServerError() *GetTriggerByNameInternalServerError {

	return &GetTriggerByNameInternalServerError{}
}

// WithPayload adds the payload to the get trigger by name internal server error response
func (o *GetTriggerByNameInternalServerError) WithPayload(payload *models.ErrorMessage) *GetTriggerByNameInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get trigger by name internal server error response
func (o *GetTriggerByNameInternalServerError) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTriggerByNameInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
