// Code generated by go-swagger; DO NOT EDIT.

package triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTriggerByNameParams creates a new GetTriggerByNameParams object
// no default values defined in spec.
func NewGetTriggerByNameParams() GetTriggerByNameParams {

	return GetTriggerByNameParams{}
}

// GetTriggerByNameParams contains all the bound params for the get trigger by name operation
// typically these are obtained from a http.Request
//
// swagger:parameters getTriggerByName
type GetTriggerByNameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The entity namespace
	  Required: true
	  In: path
	*/
	Namespace string
	/*Name of trigger to fetch
	  Required: true
	  In: path
	*/
	TriggerName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTriggerByNameParams() beforehand.
func (o *GetTriggerByNameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rNamespace, rhkNamespace, _ := route.Params.GetOK("namespace")
	if err := o.bindNamespace(rNamespace, rhkNamespace, route.Formats); err != nil {
		res = append(res, err)
	}

	rTriggerName, rhkTriggerName, _ := route.Params.GetOK("triggerName")
	if err := o.bindTriggerName(rTriggerName, rhkTriggerName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTriggerByNameParams) bindNamespace(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Namespace = raw

	return nil
}

func (o *GetTriggerByNameParams) bindTriggerName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.TriggerName = raw

	return nil
}
