// Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/projectodd/kwsk/models"
)

// DeleteWebNamespacePackageNameActionNameExtensionHandlerFunc turns a function with the right signature into a delete web namespace package name action name extension handler
type DeleteWebNamespacePackageNameActionNameExtensionHandlerFunc func(DeleteWebNamespacePackageNameActionNameExtensionParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteWebNamespacePackageNameActionNameExtensionHandlerFunc) Handle(params DeleteWebNamespacePackageNameActionNameExtensionParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteWebNamespacePackageNameActionNameExtensionHandler interface for that can handle valid delete web namespace package name action name extension params
type DeleteWebNamespacePackageNameActionNameExtensionHandler interface {
	Handle(DeleteWebNamespacePackageNameActionNameExtensionParams, *models.Principal) middleware.Responder
}

// NewDeleteWebNamespacePackageNameActionNameExtension creates a new http.Handler for the delete web namespace package name action name extension operation
func NewDeleteWebNamespacePackageNameActionNameExtension(ctx *middleware.Context, handler DeleteWebNamespacePackageNameActionNameExtensionHandler) *DeleteWebNamespacePackageNameActionNameExtension {
	return &DeleteWebNamespacePackageNameActionNameExtension{Context: ctx, Handler: handler}
}

/*DeleteWebNamespacePackageNameActionNameExtension swagger:route DELETE /web/{namespace}/{packageName}/{actionName}.{extension} Actions deleteWebNamespacePackageNameActionNameExtension

DeleteWebNamespacePackageNameActionNameExtension delete web namespace package name action name extension API

*/
type DeleteWebNamespacePackageNameActionNameExtension struct {
	Context *middleware.Context
	Handler DeleteWebNamespacePackageNameActionNameExtensionHandler
}

func (o *DeleteWebNamespacePackageNameActionNameExtension) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteWebNamespacePackageNameActionNameExtensionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteWebNamespacePackageNameActionNameExtensionDefaultBody delete web namespace package name action name extension default body
// swagger:model DeleteWebNamespacePackageNameActionNameExtensionDefaultBody
type DeleteWebNamespacePackageNameActionNameExtensionDefaultBody interface{}
