// Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllActionsHandlerFunc turns a function with the right signature into a get all actions handler
type GetAllActionsHandlerFunc func(GetAllActionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllActionsHandlerFunc) Handle(params GetAllActionsParams) middleware.Responder {
	return fn(params)
}

// GetAllActionsHandler interface for that can handle valid get all actions params
type GetAllActionsHandler interface {
	Handle(GetAllActionsParams) middleware.Responder
}

// NewGetAllActions creates a new http.Handler for the get all actions operation
func NewGetAllActions(ctx *middleware.Context, handler GetAllActionsHandler) *GetAllActions {
	return &GetAllActions{Context: ctx, Handler: handler}
}

/*GetAllActions swagger:route GET /namespaces/{namespace}/actions Actions getAllActions

Get all actions

Get all actions

*/
type GetAllActions struct {
	Context *middleware.Context
	Handler GetAllActionsHandler
}

func (o *GetAllActions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllActionsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
