// Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/projectodd/kwsk/models"
)

// GetWebNamespacePackageNameActionNameExtensionHandlerFunc turns a function with the right signature into a get web namespace package name action name extension handler
type GetWebNamespacePackageNameActionNameExtensionHandlerFunc func(GetWebNamespacePackageNameActionNameExtensionParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWebNamespacePackageNameActionNameExtensionHandlerFunc) Handle(params GetWebNamespacePackageNameActionNameExtensionParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetWebNamespacePackageNameActionNameExtensionHandler interface for that can handle valid get web namespace package name action name extension params
type GetWebNamespacePackageNameActionNameExtensionHandler interface {
	Handle(GetWebNamespacePackageNameActionNameExtensionParams, *models.Principal) middleware.Responder
}

// NewGetWebNamespacePackageNameActionNameExtension creates a new http.Handler for the get web namespace package name action name extension operation
func NewGetWebNamespacePackageNameActionNameExtension(ctx *middleware.Context, handler GetWebNamespacePackageNameActionNameExtensionHandler) *GetWebNamespacePackageNameActionNameExtension {
	return &GetWebNamespacePackageNameActionNameExtension{Context: ctx, Handler: handler}
}

/*GetWebNamespacePackageNameActionNameExtension swagger:route GET /web/{namespace}/{packageName}/{actionName}.{extension} Actions getWebNamespacePackageNameActionNameExtension

GetWebNamespacePackageNameActionNameExtension get web namespace package name action name extension API

*/
type GetWebNamespacePackageNameActionNameExtension struct {
	Context *middleware.Context
	Handler GetWebNamespacePackageNameActionNameExtensionHandler
}

func (o *GetWebNamespacePackageNameActionNameExtension) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetWebNamespacePackageNameActionNameExtensionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetWebNamespacePackageNameActionNameExtensionDefaultBody get web namespace package name action name extension default body
// swagger:model GetWebNamespacePackageNameActionNameExtensionDefaultBody
type GetWebNamespacePackageNameActionNameExtensionDefaultBody interface{}
