// Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetActionByNameHandlerFunc turns a function with the right signature into a get action by name handler
type GetActionByNameHandlerFunc func(GetActionByNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetActionByNameHandlerFunc) Handle(params GetActionByNameParams) middleware.Responder {
	return fn(params)
}

// GetActionByNameHandler interface for that can handle valid get action by name params
type GetActionByNameHandler interface {
	Handle(GetActionByNameParams) middleware.Responder
}

// NewGetActionByName creates a new http.Handler for the get action by name operation
func NewGetActionByName(ctx *middleware.Context, handler GetActionByNameHandler) *GetActionByName {
	return &GetActionByName{Context: ctx, Handler: handler}
}

/*GetActionByName swagger:route GET /namespaces/{namespace}/actions/{actionName} Actions getActionByName

Get action information

Get action information.

*/
type GetActionByName struct {
	Context *middleware.Context
	Handler GetActionByNameHandler
}

func (o *GetActionByName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetActionByNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
