// Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// InvokeActionURL generates an URL for the invoke action operation
type InvokeActionURL struct {
	ActionName string
	Namespace  string

	Blocking *string
	Result   *string
	Timeout  *int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *InvokeActionURL) WithBasePath(bp string) *InvokeActionURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *InvokeActionURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *InvokeActionURL) Build() (*url.URL, error) {
	var resultUrl url.URL

	var _path = "/namespaces/{namespace}/actions/{actionName}"

	actionName := o.ActionName
	if actionName != "" {
		_path = strings.Replace(_path, "{actionName}", actionName, -1)
	} else {
		return nil, errors.New("ActionName is required on InvokeActionURL")
	}

	namespace := o.Namespace
	if namespace != "" {
		_path = strings.Replace(_path, "{namespace}", namespace, -1)
	} else {
		return nil, errors.New("Namespace is required on InvokeActionURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	resultUrl.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var blocking string
	if o.Blocking != nil {
		blocking = *o.Blocking
	}
	if blocking != "" {
		qs.Set("blocking", blocking)
	}

	var result string
	if o.Result != nil {
		result = *o.Result
	}
	if result != "" {
		qs.Set("result", result)
	}

	var timeout string
	if o.Timeout != nil {
		timeout = swag.FormatInt64(*o.Timeout)
	}
	if timeout != "" {
		qs.Set("timeout", timeout)
	}

	resultUrl.RawQuery = qs.Encode()

	return &resultUrl, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *InvokeActionURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *InvokeActionURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *InvokeActionURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on InvokeActionURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on InvokeActionURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *InvokeActionURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
