// Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/projectodd/kwsk/models"
)

// InvokeActionInPackageHandlerFunc turns a function with the right signature into a invoke action in package handler
type InvokeActionInPackageHandlerFunc func(InvokeActionInPackageParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn InvokeActionInPackageHandlerFunc) Handle(params InvokeActionInPackageParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// InvokeActionInPackageHandler interface for that can handle valid invoke action in package params
type InvokeActionInPackageHandler interface {
	Handle(InvokeActionInPackageParams, *models.Principal) middleware.Responder
}

// NewInvokeActionInPackage creates a new http.Handler for the invoke action in package operation
func NewInvokeActionInPackage(ctx *middleware.Context, handler InvokeActionInPackageHandler) *InvokeActionInPackage {
	return &InvokeActionInPackage{Context: ctx, Handler: handler}
}

/*InvokeActionInPackage swagger:route POST /namespaces/{namespace}/actions/{packageName}/{actionName} Actions invokeActionInPackage

Invoke an action

Invoke an action

*/
type InvokeActionInPackage struct {
	Context *middleware.Context
	Handler InvokeActionInPackageHandler
}

func (o *InvokeActionInPackage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewInvokeActionInPackageParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
