// Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/projectodd/kwsk/models"
)

// InvokeActionHandlerFunc turns a function with the right signature into a invoke action handler
type InvokeActionHandlerFunc func(InvokeActionParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn InvokeActionHandlerFunc) Handle(params InvokeActionParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// InvokeActionHandler interface for that can handle valid invoke action params
type InvokeActionHandler interface {
	Handle(InvokeActionParams, *models.Principal) middleware.Responder
}

// NewInvokeAction creates a new http.Handler for the invoke action operation
func NewInvokeAction(ctx *middleware.Context, handler InvokeActionHandler) *InvokeAction {
	return &InvokeAction{Context: ctx, Handler: handler}
}

/*InvokeAction swagger:route POST /namespaces/{namespace}/actions/{actionName} Actions invokeAction

Invoke an action

Invoke an action

*/
type InvokeAction struct {
	Context *middleware.Context
	Handler InvokeActionHandler
}

func (o *InvokeAction) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewInvokeActionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// InvokeActionOKBody invoke action o k body
// swagger:model InvokeActionOKBody
type InvokeActionOKBody interface{}
