// Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*PostWebNamespacePackageNameActionNameExtensionDefault any response

swagger:response postWebNamespacePackageNameActionNameExtensionDefault
*/
type PostWebNamespacePackageNameActionNameExtensionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload PostWebNamespacePackageNameActionNameExtensionDefaultBody `json:"body,omitempty"`
}

// NewPostWebNamespacePackageNameActionNameExtensionDefault creates PostWebNamespacePackageNameActionNameExtensionDefault with default headers values
func NewPostWebNamespacePackageNameActionNameExtensionDefault(code int) *PostWebNamespacePackageNameActionNameExtensionDefault {
	if code <= 0 {
		code = 500
	}

	return &PostWebNamespacePackageNameActionNameExtensionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post web namespace package name action name extension default response
func (o *PostWebNamespacePackageNameActionNameExtensionDefault) WithStatusCode(code int) *PostWebNamespacePackageNameActionNameExtensionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post web namespace package name action name extension default response
func (o *PostWebNamespacePackageNameActionNameExtensionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post web namespace package name action name extension default response
func (o *PostWebNamespacePackageNameActionNameExtensionDefault) WithPayload(payload PostWebNamespacePackageNameActionNameExtensionDefaultBody) *PostWebNamespacePackageNameActionNameExtensionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post web namespace package name action name extension default response
func (o *PostWebNamespacePackageNameActionNameExtensionDefault) SetPayload(payload PostWebNamespacePackageNameActionNameExtensionDefaultBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostWebNamespacePackageNameActionNameExtensionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
