// Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/projectodd/kwsk/models"
)

// PostWebNamespacePackageNameActionNameExtensionHandlerFunc turns a function with the right signature into a post web namespace package name action name extension handler
type PostWebNamespacePackageNameActionNameExtensionHandlerFunc func(PostWebNamespacePackageNameActionNameExtensionParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostWebNamespacePackageNameActionNameExtensionHandlerFunc) Handle(params PostWebNamespacePackageNameActionNameExtensionParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostWebNamespacePackageNameActionNameExtensionHandler interface for that can handle valid post web namespace package name action name extension params
type PostWebNamespacePackageNameActionNameExtensionHandler interface {
	Handle(PostWebNamespacePackageNameActionNameExtensionParams, *models.Principal) middleware.Responder
}

// NewPostWebNamespacePackageNameActionNameExtension creates a new http.Handler for the post web namespace package name action name extension operation
func NewPostWebNamespacePackageNameActionNameExtension(ctx *middleware.Context, handler PostWebNamespacePackageNameActionNameExtensionHandler) *PostWebNamespacePackageNameActionNameExtension {
	return &PostWebNamespacePackageNameActionNameExtension{Context: ctx, Handler: handler}
}

/*PostWebNamespacePackageNameActionNameExtension swagger:route POST /web/{namespace}/{packageName}/{actionName}.{extension} Actions postWebNamespacePackageNameActionNameExtension

PostWebNamespacePackageNameActionNameExtension post web namespace package name action name extension API

*/
type PostWebNamespacePackageNameActionNameExtension struct {
	Context *middleware.Context
	Handler PostWebNamespacePackageNameActionNameExtensionHandler
}

func (o *PostWebNamespacePackageNameActionNameExtension) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostWebNamespacePackageNameActionNameExtensionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostWebNamespacePackageNameActionNameExtensionDefaultBody post web namespace package name action name extension default body
// swagger:model PostWebNamespacePackageNameActionNameExtensionDefaultBody
type PostWebNamespacePackageNameActionNameExtensionDefaultBody interface{}
