// Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/projectodd/kwsk/models"
)

// UpdateActionInPackageHandlerFunc turns a function with the right signature into a update action in package handler
type UpdateActionInPackageHandlerFunc func(UpdateActionInPackageParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateActionInPackageHandlerFunc) Handle(params UpdateActionInPackageParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateActionInPackageHandler interface for that can handle valid update action in package params
type UpdateActionInPackageHandler interface {
	Handle(UpdateActionInPackageParams, *models.Principal) middleware.Responder
}

// NewUpdateActionInPackage creates a new http.Handler for the update action in package operation
func NewUpdateActionInPackage(ctx *middleware.Context, handler UpdateActionInPackageHandler) *UpdateActionInPackage {
	return &UpdateActionInPackage{Context: ctx, Handler: handler}
}

/*UpdateActionInPackage swagger:route PUT /namespaces/{namespace}/actions/{packageName}/{actionName} Actions updateActionInPackage

Create or update an action

Create or update an action

*/
type UpdateActionInPackage struct {
	Context *middleware.Context
	Handler UpdateActionInPackageHandler
}

func (o *UpdateActionInPackage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateActionInPackageParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
