// Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/projectodd/kwsk/models"
)

// NewUpdateActionParams creates a new UpdateActionParams object
// no default values defined in spec.
func NewUpdateActionParams() UpdateActionParams {

	return UpdateActionParams{}
}

// UpdateActionParams contains all the bound params for the update action operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateAction
type UpdateActionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The action being updated
	  Required: true
	  In: body
	*/
	Action *models.ActionPut
	/*Name of action to fetch
	  Required: true
	  In: path
	*/
	ActionName string
	/*The entity namespace
	  Required: true
	  In: path
	*/
	Namespace string
	/*Overwrite item if it exists. Default is false.
	  In: query
	*/
	Overwrite *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateActionParams() beforehand.
func (o *UpdateActionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ActionPut
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("action", "body"))
			} else {
				res = append(res, errors.NewParseError("action", "body", "", err))
			}
		} else {

			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Action = &body
			}
		}
	} else {
		res = append(res, errors.Required("action", "body"))
	}
	rActionName, rhkActionName, _ := route.Params.GetOK("actionName")
	if err := o.bindActionName(rActionName, rhkActionName, route.Formats); err != nil {
		res = append(res, err)
	}

	rNamespace, rhkNamespace, _ := route.Params.GetOK("namespace")
	if err := o.bindNamespace(rNamespace, rhkNamespace, route.Formats); err != nil {
		res = append(res, err)
	}

	qOverwrite, qhkOverwrite, _ := qs.GetOK("overwrite")
	if err := o.bindOverwrite(qOverwrite, qhkOverwrite, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateActionParams) bindActionName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ActionName = raw

	return nil
}

func (o *UpdateActionParams) bindNamespace(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Namespace = raw

	return nil
}

func (o *UpdateActionParams) bindOverwrite(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Overwrite = &raw

	if err := o.validateOverwrite(formats); err != nil {
		return err
	}

	return nil
}

func (o *UpdateActionParams) validateOverwrite(formats strfmt.Registry) error {

	if err := validate.Enum("overwrite", "query", *o.Overwrite, []interface{}{"true", "false"}); err != nil {
		return err
	}

	return nil
}
