// Code generated by go-swagger; DO NOT EDIT.

package activations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetActivationsHandlerFunc turns a function with the right signature into a get activations handler
type GetActivationsHandlerFunc func(GetActivationsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetActivationsHandlerFunc) Handle(params GetActivationsParams) middleware.Responder {
	return fn(params)
}

// GetActivationsHandler interface for that can handle valid get activations params
type GetActivationsHandler interface {
	Handle(GetActivationsParams) middleware.Responder
}

// NewGetActivations creates a new http.Handler for the get activations operation
func NewGetActivations(ctx *middleware.Context, handler GetActivationsHandler) *GetActivations {
	return &GetActivations{Context: ctx, Handler: handler}
}

/*GetActivations swagger:route GET /namespaces/{namespace}/activations Activations getActivations

Get activation ids

Get activation ids.

*/
type GetActivations struct {
	Context *middleware.Context
	Handler GetActivationsHandler
}

func (o *GetActivations) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetActivationsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
