// Code generated by go-swagger; DO NOT EDIT.

package activations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/projectodd/kwsk/models"
)

// GetNamespacesNamespaceActivationsActivationidLogsOKCode is the HTTP code returned for type GetNamespacesNamespaceActivationsActivationidLogsOK
const GetNamespacesNamespaceActivationsActivationidLogsOKCode int = 200

/*GetNamespacesNamespaceActivationsActivationidLogsOK Return output

swagger:response getNamespacesNamespaceActivationsActivationidLogsOK
*/
type GetNamespacesNamespaceActivationsActivationidLogsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ActivationLogs `json:"body,omitempty"`
}

// NewGetNamespacesNamespaceActivationsActivationidLogsOK creates GetNamespacesNamespaceActivationsActivationidLogsOK with default headers values
func NewGetNamespacesNamespaceActivationsActivationidLogsOK() *GetNamespacesNamespaceActivationsActivationidLogsOK {

	return &GetNamespacesNamespaceActivationsActivationidLogsOK{}
}

// WithPayload adds the payload to the get namespaces namespace activations activationid logs o k response
func (o *GetNamespacesNamespaceActivationsActivationidLogsOK) WithPayload(payload *models.ActivationLogs) *GetNamespacesNamespaceActivationsActivationidLogsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get namespaces namespace activations activationid logs o k response
func (o *GetNamespacesNamespaceActivationsActivationidLogsOK) SetPayload(payload *models.ActivationLogs) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNamespacesNamespaceActivationsActivationidLogsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNamespacesNamespaceActivationsActivationidLogsUnauthorizedCode is the HTTP code returned for type GetNamespacesNamespaceActivationsActivationidLogsUnauthorized
const GetNamespacesNamespaceActivationsActivationidLogsUnauthorizedCode int = 401

/*GetNamespacesNamespaceActivationsActivationidLogsUnauthorized Unauthorized request

swagger:response getNamespacesNamespaceActivationsActivationidLogsUnauthorized
*/
type GetNamespacesNamespaceActivationsActivationidLogsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetNamespacesNamespaceActivationsActivationidLogsUnauthorized creates GetNamespacesNamespaceActivationsActivationidLogsUnauthorized with default headers values
func NewGetNamespacesNamespaceActivationsActivationidLogsUnauthorized() *GetNamespacesNamespaceActivationsActivationidLogsUnauthorized {

	return &GetNamespacesNamespaceActivationsActivationidLogsUnauthorized{}
}

// WithPayload adds the payload to the get namespaces namespace activations activationid logs unauthorized response
func (o *GetNamespacesNamespaceActivationsActivationidLogsUnauthorized) WithPayload(payload *models.ErrorMessage) *GetNamespacesNamespaceActivationsActivationidLogsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get namespaces namespace activations activationid logs unauthorized response
func (o *GetNamespacesNamespaceActivationsActivationidLogsUnauthorized) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNamespacesNamespaceActivationsActivationidLogsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNamespacesNamespaceActivationsActivationidLogsNotFoundCode is the HTTP code returned for type GetNamespacesNamespaceActivationsActivationidLogsNotFound
const GetNamespacesNamespaceActivationsActivationidLogsNotFoundCode int = 404

/*GetNamespacesNamespaceActivationsActivationidLogsNotFound Item not found

swagger:response getNamespacesNamespaceActivationsActivationidLogsNotFound
*/
type GetNamespacesNamespaceActivationsActivationidLogsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetNamespacesNamespaceActivationsActivationidLogsNotFound creates GetNamespacesNamespaceActivationsActivationidLogsNotFound with default headers values
func NewGetNamespacesNamespaceActivationsActivationidLogsNotFound() *GetNamespacesNamespaceActivationsActivationidLogsNotFound {

	return &GetNamespacesNamespaceActivationsActivationidLogsNotFound{}
}

// WithPayload adds the payload to the get namespaces namespace activations activationid logs not found response
func (o *GetNamespacesNamespaceActivationsActivationidLogsNotFound) WithPayload(payload *models.ErrorMessage) *GetNamespacesNamespaceActivationsActivationidLogsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get namespaces namespace activations activationid logs not found response
func (o *GetNamespacesNamespaceActivationsActivationidLogsNotFound) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNamespacesNamespaceActivationsActivationidLogsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNamespacesNamespaceActivationsActivationidLogsInternalServerErrorCode is the HTTP code returned for type GetNamespacesNamespaceActivationsActivationidLogsInternalServerError
const GetNamespacesNamespaceActivationsActivationidLogsInternalServerErrorCode int = 500

/*GetNamespacesNamespaceActivationsActivationidLogsInternalServerError Server error

swagger:response getNamespacesNamespaceActivationsActivationidLogsInternalServerError
*/
type GetNamespacesNamespaceActivationsActivationidLogsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetNamespacesNamespaceActivationsActivationidLogsInternalServerError creates GetNamespacesNamespaceActivationsActivationidLogsInternalServerError with default headers values
func NewGetNamespacesNamespaceActivationsActivationidLogsInternalServerError() *GetNamespacesNamespaceActivationsActivationidLogsInternalServerError {

	return &GetNamespacesNamespaceActivationsActivationidLogsInternalServerError{}
}

// WithPayload adds the payload to the get namespaces namespace activations activationid logs internal server error response
func (o *GetNamespacesNamespaceActivationsActivationidLogsInternalServerError) WithPayload(payload *models.ErrorMessage) *GetNamespacesNamespaceActivationsActivationidLogsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get namespaces namespace activations activationid logs internal server error response
func (o *GetNamespacesNamespaceActivationsActivationidLogsInternalServerError) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNamespacesNamespaceActivationsActivationidLogsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
