// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/projectodd/kwsk/models"
)

// GetRuleByNameHandlerFunc turns a function with the right signature into a get rule by name handler
type GetRuleByNameHandlerFunc func(GetRuleByNameParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRuleByNameHandlerFunc) Handle(params GetRuleByNameParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetRuleByNameHandler interface for that can handle valid get rule by name params
type GetRuleByNameHandler interface {
	Handle(GetRuleByNameParams, *models.Principal) middleware.Responder
}

// NewGetRuleByName creates a new http.Handler for the get rule by name operation
func NewGetRuleByName(ctx *middleware.Context, handler GetRuleByNameHandler) *GetRuleByName {
	return &GetRuleByName{Context: ctx, Handler: handler}
}

/*GetRuleByName swagger:route GET /namespaces/{namespace}/rules/{ruleName} Rules getRuleByName

Get rule information

Get rule information

*/
type GetRuleByName struct {
	Context *middleware.Context
	Handler GetRuleByNameHandler
}

func (o *GetRuleByName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRuleByNameParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
