// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSetStateParams creates a new SetStateParams object
// no default values defined in spec.
func NewSetStateParams() SetStateParams {

	return SetStateParams{}
}

// SetStateParams contains all the bound params for the set state operation
// typically these are obtained from a http.Request
//
// swagger:parameters setState
type SetStateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The entity namespace
	  Required: true
	  In: path
	*/
	Namespace string
	/*Name of rule to update
	  Required: true
	  In: path
	*/
	RuleName string
	/*Set state to enable or disable
	  Required: true
	  In: query
	*/
	State string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSetStateParams() beforehand.
func (o *SetStateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rNamespace, rhkNamespace, _ := route.Params.GetOK("namespace")
	if err := o.bindNamespace(rNamespace, rhkNamespace, route.Formats); err != nil {
		res = append(res, err)
	}

	rRuleName, rhkRuleName, _ := route.Params.GetOK("ruleName")
	if err := o.bindRuleName(rRuleName, rhkRuleName, route.Formats); err != nil {
		res = append(res, err)
	}

	qState, qhkState, _ := qs.GetOK("state")
	if err := o.bindState(qState, qhkState, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SetStateParams) bindNamespace(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Namespace = raw

	return nil
}

func (o *SetStateParams) bindRuleName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.RuleName = raw

	return nil
}

func (o *SetStateParams) bindState(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("state", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("state", "query", raw); err != nil {
		return err
	}

	o.State = raw

	if err := o.validateState(formats); err != nil {
		return err
	}

	return nil
}

func (o *SetStateParams) validateState(formats strfmt.Registry) error {

	if err := validate.Enum("state", "query", o.State, []interface{}{"disabled", "enabled"}); err != nil {
		return err
	}

	return nil
}
