// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/projectodd/kwsk/models"
)

// SetStateHandlerFunc turns a function with the right signature into a set state handler
type SetStateHandlerFunc func(SetStateParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SetStateHandlerFunc) Handle(params SetStateParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SetStateHandler interface for that can handle valid set state params
type SetStateHandler interface {
	Handle(SetStateParams, *models.Principal) middleware.Responder
}

// NewSetState creates a new http.Handler for the set state operation
func NewSetState(ctx *middleware.Context, handler SetStateHandler) *SetState {
	return &SetState{Context: ctx, Handler: handler}
}

/*SetState swagger:route POST /namespaces/{namespace}/rules/{ruleName} Rules setState

Enable or disable a rule

Enable or disable a rule

*/
type SetState struct {
	Context *middleware.Context
	Handler SetStateHandler
}

func (o *SetState) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSetStateParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
