// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SetStateHandlerFunc turns a function with the right signature into a set state handler
type SetStateHandlerFunc func(SetStateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SetStateHandlerFunc) Handle(params SetStateParams) middleware.Responder {
	return fn(params)
}

// SetStateHandler interface for that can handle valid set state params
type SetStateHandler interface {
	Handle(SetStateParams) middleware.Responder
}

// NewSetState creates a new http.Handler for the set state operation
func NewSetState(ctx *middleware.Context, handler SetStateHandler) *SetState {
	return &SetState{Context: ctx, Handler: handler}
}

/*SetState swagger:route POST /namespaces/{namespace}/rules/{ruleName} Rules setState

Enable or disable a rule

Enable or disable a rule

*/
type SetState struct {
	Context *middleware.Context
	Handler SetStateHandler
}

func (o *SetState) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSetStateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
