// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/projectodd/kwsk/models"
)

// DeletePackageHandlerFunc turns a function with the right signature into a delete package handler
type DeletePackageHandlerFunc func(DeletePackageParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePackageHandlerFunc) Handle(params DeletePackageParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeletePackageHandler interface for that can handle valid delete package params
type DeletePackageHandler interface {
	Handle(DeletePackageParams, *models.Principal) middleware.Responder
}

// NewDeletePackage creates a new http.Handler for the delete package operation
func NewDeletePackage(ctx *middleware.Context, handler DeletePackageHandler) *DeletePackage {
	return &DeletePackage{Context: ctx, Handler: handler}
}

/*DeletePackage swagger:route DELETE /namespaces/{namespace}/packages/{packageName} Packages deletePackage

Delete a package

Delete a package

*/
type DeletePackage struct {
	Context *middleware.Context
	Handler DeletePackageHandler
}

func (o *DeletePackage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeletePackageParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
