// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllPackagesHandlerFunc turns a function with the right signature into a get all packages handler
type GetAllPackagesHandlerFunc func(GetAllPackagesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllPackagesHandlerFunc) Handle(params GetAllPackagesParams) middleware.Responder {
	return fn(params)
}

// GetAllPackagesHandler interface for that can handle valid get all packages params
type GetAllPackagesHandler interface {
	Handle(GetAllPackagesParams) middleware.Responder
}

// NewGetAllPackages creates a new http.Handler for the get all packages operation
func NewGetAllPackages(ctx *middleware.Context, handler GetAllPackagesHandler) *GetAllPackages {
	return &GetAllPackages{Context: ctx, Handler: handler}
}

/*GetAllPackages swagger:route GET /namespaces/{namespace}/packages Packages getAllPackages

Get all packages

Get all packages

*/
type GetAllPackages struct {
	Context *middleware.Context
	Handler GetAllPackagesHandler
}

func (o *GetAllPackages) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllPackagesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
