// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/projectodd/kwsk/models"
)

// GetAllPackagesOKCode is the HTTP code returned for type GetAllPackagesOK
const GetAllPackagesOKCode int = 200

/*GetAllPackagesOK Packages response

swagger:response getAllPackagesOK
*/
type GetAllPackagesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Package `json:"body,omitempty"`
}

// NewGetAllPackagesOK creates GetAllPackagesOK with default headers values
func NewGetAllPackagesOK() *GetAllPackagesOK {

	return &GetAllPackagesOK{}
}

// WithPayload adds the payload to the get all packages o k response
func (o *GetAllPackagesOK) WithPayload(payload []*models.Package) *GetAllPackagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all packages o k response
func (o *GetAllPackagesOK) SetPayload(payload []*models.Package) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllPackagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Package, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetAllPackagesUnauthorizedCode is the HTTP code returned for type GetAllPackagesUnauthorized
const GetAllPackagesUnauthorizedCode int = 401

/*GetAllPackagesUnauthorized Unauthorized request

swagger:response getAllPackagesUnauthorized
*/
type GetAllPackagesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetAllPackagesUnauthorized creates GetAllPackagesUnauthorized with default headers values
func NewGetAllPackagesUnauthorized() *GetAllPackagesUnauthorized {

	return &GetAllPackagesUnauthorized{}
}

// WithPayload adds the payload to the get all packages unauthorized response
func (o *GetAllPackagesUnauthorized) WithPayload(payload *models.ErrorMessage) *GetAllPackagesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all packages unauthorized response
func (o *GetAllPackagesUnauthorized) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllPackagesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllPackagesInternalServerErrorCode is the HTTP code returned for type GetAllPackagesInternalServerError
const GetAllPackagesInternalServerErrorCode int = 500

/*GetAllPackagesInternalServerError Server error

swagger:response getAllPackagesInternalServerError
*/
type GetAllPackagesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetAllPackagesInternalServerError creates GetAllPackagesInternalServerError with default headers values
func NewGetAllPackagesInternalServerError() *GetAllPackagesInternalServerError {

	return &GetAllPackagesInternalServerError{}
}

// WithPayload adds the payload to the get all packages internal server error response
func (o *GetAllPackagesInternalServerError) WithPayload(payload *models.ErrorMessage) *GetAllPackagesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all packages internal server error response
func (o *GetAllPackagesInternalServerError) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllPackagesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
