// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAlPackagesHandlerFunc turns a function with the right signature into a get al packages handler
type GetAlPackagesHandlerFunc func(GetAlPackagesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAlPackagesHandlerFunc) Handle(params GetAlPackagesParams) middleware.Responder {
	return fn(params)
}

// GetAlPackagesHandler interface for that can handle valid get al packages params
type GetAlPackagesHandler interface {
	Handle(GetAlPackagesParams) middleware.Responder
}

// NewGetAlPackages creates a new http.Handler for the get al packages operation
func NewGetAlPackages(ctx *middleware.Context, handler GetAlPackagesHandler) *GetAlPackages {
	return &GetAlPackages{Context: ctx, Handler: handler}
}

/*GetAlPackages swagger:route GET /namespaces/{namespace}/packages Packages getAlPackages

Get all packages

Get all packages

*/
type GetAlPackages struct {
	Context *middleware.Context
	Handler GetAlPackagesHandler
}

func (o *GetAlPackages) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAlPackagesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
