// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdatePackageHandlerFunc turns a function with the right signature into a update package handler
type UpdatePackageHandlerFunc func(UpdatePackageParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdatePackageHandlerFunc) Handle(params UpdatePackageParams) middleware.Responder {
	return fn(params)
}

// UpdatePackageHandler interface for that can handle valid update package params
type UpdatePackageHandler interface {
	Handle(UpdatePackageParams) middleware.Responder
}

// NewUpdatePackage creates a new http.Handler for the update package operation
func NewUpdatePackage(ctx *middleware.Context, handler UpdatePackageHandler) *UpdatePackage {
	return &UpdatePackage{Context: ctx, Handler: handler}
}

/*UpdatePackage swagger:route PUT /namespaces/{namespace}/packages/{packageName} Packages updatePackage

Create or update a package

Create or update a package

*/
type UpdatePackage struct {
	Context *middleware.Context
	Handler UpdatePackageHandler
}

func (o *UpdatePackage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdatePackageParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
