// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ActionExec definition of the action, such as javascript code or the name of a container
// swagger:model ActionExec
type ActionExec struct {

	// The code to execute when kind is not 'blackbox'
	Code string `json:"code,omitempty"`

	// container image name when kind is 'blackbox'
	Image string `json:"image,omitempty"`

	// optional zipfile reference when code kind is 'nodejs'
	Init string `json:"init,omitempty"`

	// the type of action
	// Required: true
	// Enum: [nodejs:6 nodejs:8 python:2 python:3 swift:3.1.1 java blackbox]
	Kind *string `json:"kind"`
}

// Validate validates this action exec
func (m *ActionExec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKind(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var actionExecTypeKindPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["nodejs:6","nodejs:8","python:2","python:3","swift:3.1.1","java","blackbox"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		actionExecTypeKindPropEnum = append(actionExecTypeKindPropEnum, v)
	}
}

const (

	// ActionExecKindNodejs6 captures enum value "nodejs:6"
	ActionExecKindNodejs6 string = "nodejs:6"

	// ActionExecKindNodejs8 captures enum value "nodejs:8"
	ActionExecKindNodejs8 string = "nodejs:8"

	// ActionExecKindPython2 captures enum value "python:2"
	ActionExecKindPython2 string = "python:2"

	// ActionExecKindPython3 captures enum value "python:3"
	ActionExecKindPython3 string = "python:3"

	// ActionExecKindSwift311 captures enum value "swift:3.1.1"
	ActionExecKindSwift311 string = "swift:3.1.1"

	// ActionExecKindJava captures enum value "java"
	ActionExecKindJava string = "java"

	// ActionExecKindBlackbox captures enum value "blackbox"
	ActionExecKindBlackbox string = "blackbox"
)

// prop value enum
func (m *ActionExec) validateKindEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, actionExecTypeKindPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ActionExec) validateKind(formats strfmt.Registry) error {

	if err := validate.Required("kind", "body", m.Kind); err != nil {
		return err
	}

	// value enum
	if err := m.validateKindEnum("kind", "body", *m.Kind); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ActionExec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionExec) UnmarshalBinary(b []byte) error {
	var res ActionExec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
