// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ActivationStderr activation stderr
// swagger:model ActivationStderr
type ActivationStderr struct {

	// Standard error of an activation
	Stderr string `json:"stderr,omitempty"`
}

// Validate validates this activation stderr
func (m *ActivationStderr) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActivationStderr) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActivationStderr) UnmarshalBinary(b []byte) error {
	var res ActivationStderr
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
