// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ActivationLogs activation logs
// swagger:model ActivationLogs
type ActivationLogs struct {

	// Interleaved standard output and error of an activation
	Logs []string `json:"logs"`
}

// Validate validates this activation logs
func (m *ActivationLogs) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActivationLogs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActivationLogs) UnmarshalBinary(b []byte) error {
	var res ActivationLogs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
