// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// KeyValue key value
// swagger:model KeyValue
type KeyValue struct {

	// key
	Key string `json:"key,omitempty"`

	// Any JSON value
	Value interface{} `json:"value,omitempty"`
}

// Validate validates this key value
func (m *KeyValue) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KeyValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KeyValue) UnmarshalBinary(b []byte) error {
	var res KeyValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
