// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RulePut A restricted Rule view that elides properties that are auto-assigned or derived from the URI (i.e., the namespace and name).
// swagger:model RulePut
type RulePut struct {

	// Name of the action
	// Min Length: 1
	Action string `json:"action,omitempty"`

	// Whether to publish the item or not
	Publish bool `json:"publish,omitempty"`

	// Name of the trigger
	// Min Length: 1
	Trigger string `json:"trigger,omitempty"`

	// Semantic version of the item
	// Min Length: 1
	Version string `json:"version,omitempty"`
}

// Validate validates this rule put
func (m *RulePut) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTrigger(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RulePut) validateAction(formats strfmt.Registry) error {

	if swag.IsZero(m.Action) { // not required
		return nil
	}

	if err := validate.MinLength("action", "body", string(m.Action), 1); err != nil {
		return err
	}

	return nil
}

func (m *RulePut) validateTrigger(formats strfmt.Registry) error {

	if swag.IsZero(m.Trigger) { // not required
		return nil
	}

	if err := validate.MinLength("trigger", "body", string(m.Trigger), 1); err != nil {
		return err
	}

	return nil
}

func (m *RulePut) validateVersion(formats strfmt.Registry) error {

	if swag.IsZero(m.Version) { // not required
		return nil
	}

	if err := validate.MinLength("version", "body", string(m.Version), 1); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RulePut) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RulePut) UnmarshalBinary(b []byte) error {
	var res RulePut
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
